# Generated by Django 4.0.4 on 2022-06-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('login', models.CharField(default='', max_length=64, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=23, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert_on_festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre_and_intruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.genre')),
                ('intrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_for_concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.AddField(
            model_name='artist',
            name='band_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.band'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='nickname',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='scene_name',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='band',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='festival',
            name='music_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.genre'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AddField(
            model_name='ticket_for_concert',
            name='concert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.concert'),
        ),
        migrations.AddField(
            model_name='ticket_for_concert',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.ticket'),
        ),
        migrations.AddField(
            model_name='concert_on_festival',
            name='concert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.concert'),
        ),
        migrations.AddField(
            model_name='concert_on_festival',
            name='festival_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.festival'),
        ),
    ]
