# Generated by Django 4.0.4 on 2022-06-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_client_concert_on_festival_genre_and_intruments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='time_start',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='time_end',
        ),
    ]
